### ISSUE TITLE
点击start 后，在小米3 手机上没反应

### ISSUE THREAD

**Issue by tianshaokai** [Kyson/BalloonPerformer#1]

**Comment by Kyson** [comment]
@tianshaokai 我拿同事的小米3试过了，是可以的。

你可能是关闭了BalloonPerformer的悬浮窗权限。打开试试。

**Comment by tianshaokai** [comment]
嗯嗯，，谢谢了，我忘记了权限了，能否留下你的qq联系方式啊，交流学习自定义view
